#Postgresql config
spring.datasource.url=jdbc:postgresql://dpg-db0a55k9v7es73aihk40-a.singapore-postgres.render.com/moneymanager_dk6m
spring.datasource.username=moneymanager_dk6m_user
spring.datasource.password=93Lw4pZMQngGKS8WbSKs0fl3isfKXbsc
